# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8023baf1fb9236926540f6c9d91a32cf4a8c05c101cda8ec0839da9d803578ecdfd9ef593d606c867bb793f76bfae98fa95bbe2bc6105b6eb17fea747e537ac4

test:
  secret_key_base: e975920bc210ec10208010b2fda31708d58fa8ce7f387b6a9276f6e4a01b28f975d542300fa32eec57452f87a2ffe74388b6ee312992fce2e61f65a8e97a8c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
